### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by bantle1984** [karlvr/homebridge-roomba2#60]
Good Day, 

below is the erro i am getting, any help or support would be greatly appreciated.

blid is my email address right?

if so my password and id is right for sure

9/16/2021, 7:53:32 PMRoomba2 Bridge starting
9/16/2021, 7:53:35 PMRoomba2 BridgeLoaded plugin 'homebridge-roomba2'
9/16/2021, 7:53:35 PMRoomba2 BridgeLoading 1 accessories...
9/16/2021, 7:53:35 PMRoomba2 BridgeRoombaEnabling keepAlive
9/16/2021, 7:53:35 PMRoomba2 BridgeBridge is running on port 51876.
9/16/2021, 7:53:36 PMRoomba2 BridgeERRORError: Connection refused: Identifier rejected
    at MqttClient._handleConnack (/var/lib/hoobs/roomba2bridge/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/var/lib/hoobs/roomba2bridge/node_modules/mqtt/lib/client.js:350:12)
    at work (/var/lib/hoobs/roomba2bridge/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/var/lib/hoobs/roomba2bridge/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/var/lib/hoobs/roomba2bridge/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/var/lib/hoobs/roomba2bridge/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/var/lib/hoobs/roomba2bridge/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (internal/streams/readable.js:726:22)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
9/16/2021, 7:53:38 PMRoomba2 BridgeERRORError: Connection refused: Identifier rejected
    at MqttClient._handleConnack (/var/lib/hoobs/roomba2bridge/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/var/lib/hoobs/roomba2bridge/node_modules/mqtt/lib/client.js:350:12)
    at work (/var/lib/hoobs/roomba2bridge/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/var/lib/hoobs/roomba2bridge/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/var/lib/hoobs/roomba2bridge/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/var/lib/hoobs/roomba2bridge/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/var/lib/hoobs/roomba2bridge/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (internal/streams/readable.js:726:22)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by rcoletti116** [comment]
The blid is a local device ID that you need to get directly from the vacuum by following the setup steps in the readme. Your email and password for the iRobot app aren’t used.
