### ISSUE TITLE
Error: Connecting Refused: Bad username or password

### ISSUE THREAD

**Issue by JavyTX** [karlvr/homebridge-roomba2#86]
Followed directions and got up to retrieving blid & password but upon running I am receiving the following error;

Error: Connection refused: Bad username or password
    at MqttClient._handleConnack (/var/lib/hoobs/roomba2bridge/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/var/lib/hoobs/roomba2bridge/node_modules/mqtt/lib/client.js:350:12)
    at work (/var/lib/hoobs/roomba2bridge/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/var/lib/hoobs/roomba2bridge/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/var/lib/hoobs/roomba2bridge/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/var/lib/hoobs/roomba2bridge/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/var/lib/hoobs/roomba2bridge/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (internal/streams/readable.js:726:22)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

Running plugin v1.2.2 via HOOBS

**Comment by karlvr** [comment]
Are you seeing this error when trying to get password or after getting password and configuring the plugin?

Which Roomba do you have?

Of course, double-check that you have the IP and password entered into the config correctly!
